-- ================================================================================
--                   SUPABASE SECURITY & USER ISOLATION SCRIPT
-- ================================================================================
-- This script ensures user embeddings, resume text, AI profiles, saved jobs, and
-- alert preferences are strictly isolated under each user's unique user_id.
-- Run this in your Supabase SQL Editor.

-- 1. Enable Vector Extension (if not already enabled)
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Ensure user_resumes table structure and PK/FK isolation
CREATE TABLE IF NOT EXISTS public.user_resumes (
    user_id INT PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    resume_text TEXT NOT NULL,
    embedding vector(768),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Ensure user_resume_chunks table structure and user_id indexing
CREATE TABLE IF NOT EXISTS public.user_resume_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    chunk_index INT NOT NULL,
    content TEXT NOT NULL,
    token_count INT,
    embedding vector(768),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_user_resume_chunks_user_id ON public.user_resume_chunks(user_id);

-- 4. Ensure user_ai_profiles table structure and PK/FK isolation
CREATE TABLE IF NOT EXISTS public.user_ai_profiles (
    user_id INT PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    top_skills TEXT[],
    experience_level TEXT,
    preferred_roles TEXT[],
    education TEXT,
    projects_summary TEXT,
    job_fit_score INT,
    missing_skills TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Enable Row Level Security (RLS) on user-private tables
ALTER TABLE public.user_resumes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_resume_chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_ai_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alert_preferences ENABLE ROW LEVEL SECURITY;

-- 6. Create RLS Policies so users can ONLY access their own data
-- (Note: Backend connections using SUPABASE_KEY / service_role bypass RLS automatically)

-- RLS for user_resumes
DROP POLICY IF EXISTS user_resumes_owner_policy ON public.user_resumes;
CREATE POLICY user_resumes_owner_policy ON public.user_resumes
    FOR ALL
    USING (auth.uid()::text = user_id::text)
    WITH CHECK (auth.uid()::text = user_id::text);

-- RLS for user_resume_chunks
DROP POLICY IF EXISTS user_resume_chunks_owner_policy ON public.user_resume_chunks;
CREATE POLICY user_resume_chunks_owner_policy ON public.user_resume_chunks
    FOR ALL
    USING (auth.uid()::text = user_id::text)
    WITH CHECK (auth.uid()::text = user_id::text);

-- RLS for user_ai_profiles
DROP POLICY IF EXISTS user_ai_profiles_owner_policy ON public.user_ai_profiles;
CREATE POLICY user_ai_profiles_owner_policy ON public.user_ai_profiles
    FOR ALL
    USING (auth.uid()::text = user_id::text)
    WITH CHECK (auth.uid()::text = user_id::text);

-- RLS for saved_jobs
DROP POLICY IF EXISTS saved_jobs_owner_policy ON public.saved_jobs;
CREATE POLICY saved_jobs_owner_policy ON public.saved_jobs
    FOR ALL
    USING (auth.uid()::text = user_id::text)
    WITH CHECK (auth.uid()::text = user_id::text);

-- RLS for alert_preferences
DROP POLICY IF EXISTS alert_preferences_owner_policy ON public.alert_preferences;
CREATE POLICY alert_preferences_owner_policy ON public.alert_preferences
    FOR ALL
    USING (auth.uid()::text = user_id::text)
    WITH CHECK (auth.uid()::text = user_id::text);

-- 7. PL/pgSQL Function for Vector Similarity Job Matching
CREATE OR REPLACE FUNCTION match_jobs (
    query_embedding vector(768),
    match_threshold float,
    match_count int
) RETURNS TABLE (
    id int,
    title text,
    company text,
    location text,
    salary int,
    description text,
    job_url text,
    similarity float
) AS $$
BEGIN
    RETURN QUERY
    SELECT jobs.id, jobs.title, jobs.company, jobs.location,
           jobs.salary, jobs.description, jobs.job_url,
           1 - (jobs.embedding <=> query_embedding) AS similarity
    FROM jobs
    WHERE 1 - (jobs.embedding <=> query_embedding) > match_threshold
    ORDER BY jobs.embedding <=> query_embedding ASC
    LIMIT match_count;
END;
$$ LANGUAGE plpgsql;
